[build]
builder = "go"
buildCommand = "go mod tidy && go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest"
startCommand = "migrate -path ./migrations -database \"$DATABASE_URL\" up && go run ./cmd/server"